name: lint

on:
  pull_request:
    paths:
      - src/**/*
  push:
    branches:
      - master
    paths:
      - src/**/*

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: using node 16.13.0
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: yarn install
        run: yarn --frozen-lockfile

      - name: lint check
        uses: reviewdog/action-eslint@v1
        with:
          repoter: github-check
          eslint_flags: --ext .js,.ts src
